#!/usr/bin/env python3
"""Extract [[switch_tables]] entries from the XenonRecomp corpus for the
gap-fill functions (data-referenced code ReXGlue's scan never analyzed).

ReXGlue emits unanalyzed `bctr` as a runtime indirect jump, which FATALs when
the target is a jump-table label rather than a registered function (first hit:
"Jump target 0x8250377C unresolved at bctr 0x825033AC"). XenonRecomp's
translation of the same function carries the full case list, and instruction
comments are 1:1 with guest instructions, so the bctr's guest address is
start + 4 * (#instruction comments before it).

Emits: address (of the bctr), register (switch index register), labels
(case-ordered targets) — the ReXGlue [[switch_tables]] schema.

Usage:
  gen_switch_tables.py --xr-dir .../recomp_output \
      --funcs civrev/functions_xr_gapfill.toml civrev/functions_branch_targets.toml \
      --out civrev/switch_tables_xr.toml
"""
import argparse
import glob
import os
import re
import sys

FUNC_RE = re.compile(r'PPC_FUNC_IMPL\(__imp__sub_([0-9A-F]{8})\)\s*\{')
ADDR_RE = re.compile(r'^0x([0-9A-F]{8}) = \{')
INSN_RE = re.compile(r'^\s*// (?!ERROR)[a-z.][a-z0-9._+-]*(\s|$)')
SWITCH_RE = re.compile(r'^\s*switch \(ctx\.r(\d+)\.u64\)')
CASE_RE = re.compile(r'^\s*case (\d+):')
GOTO_RE = re.compile(r'^\s*goto loc_([0-9A-F]{8});')
CALL_RE = re.compile(r'^\s*sub_([0-9A-F]{8})\(ctx, base\);')
ERR_RE = re.compile(r'^\s*// ERROR: 0x([0-9A-F]{8})')


def parse_function(lines, start_addr):
    """Yield (bctr_addr, register, labels) for each switch in one function."""
    insn_count = 0
    i = 0
    while i < len(lines):
        line = lines[i]
        if INSN_RE.match(line):
            insn_count += 1
            if line.strip() == '// bctr' and i + 1 < len(lines):
                m = SWITCH_RE.match(lines[i + 1])
                if m:
                    bctr_addr = start_addr + 4 * (insn_count - 1)
                    reg = int(m.group(1))
                    labels = {}
                    pending = []
                    j = i + 2
                    while j < len(lines) and not lines[j].strip().startswith('}'):
                        cm = CASE_RE.match(lines[j])
                        if cm:
                            pending.append(int(cm.group(1)))
                        else:
                            t = (GOTO_RE.match(lines[j]) or CALL_RE.match(lines[j])
                                 or ERR_RE.match(lines[j]))
                            if t and pending:
                                for c in pending:
                                    labels[c] = int(t.group(1), 16)
                                pending = []
                        j += 1
                    if labels and max(labels) == len(labels) - 1:
                        yield (bctr_addr, reg,
                               [labels[c] for c in range(len(labels))])
                    else:
                        print(f'WARN: sparse/odd case list at bctr '
                              f'0x{bctr_addr:08X} (skipped)', file=sys.stderr)
        i += 1


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument('--xr-dir', required=True)
    ap.add_argument('--funcs', nargs='+', required=True,
                    help='TOML files whose [functions] keys scope extraction')
    ap.add_argument('--out', required=True)
    args = ap.parse_args()

    wanted = set()
    for path in args.funcs:
        for line in open(path):
            m = ADDR_RE.match(line)
            if m:
                wanted.add(m.group(1))
    if not wanted:
        print('no [functions] addresses found in --funcs', file=sys.stderr)
        return 1

    tables = []
    for fn in sorted(glob.glob(os.path.join(args.xr_dir, 'ppc_recomp.*.cpp'))):
        with open(fn) as f:
            text = f.read()
        for m in FUNC_RE.finditer(text):
            addr = m.group(1)
            if addr not in wanted:
                continue
            body_start = m.end()
            body_end = text.find('\n}', body_start)
            body = text[body_start:body_end].splitlines()
            tables.extend(parse_function(body, int(addr, 16)))

    tables.sort()
    with open(args.out, 'w') as out:
        out.write(
            '# GENERATED by tools/gen_switch_tables.py — do not hand-edit.\n'
            '# Jump tables inside gap-fill functions (regions ReXGlue never\n'
            '# scanned); extracted from the XenonRecomp corpus translations.\n')
        for bctr, reg, labels in tables:
            out.write('\n[[switch_tables]]\n')
            out.write(f'address = 0x{bctr:08X}\n')
            out.write(f'register = {reg}\n')
            out.write('labels = [\n')
            for lab in labels:
                out.write(f'    0x{lab:08X},\n')
            out.write(']\n')
    print(f'{len(tables)} switch tables -> {args.out}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
