#!/usr/bin/env python3
"""Generate [functions] gap-fill entries for ReXGlue from the XenonRecomp corpus.

ReXGlue's flow analysis only finds functions reachable from scanned roots;
functions reached exclusively through data (vtables, function-pointer tables)
are invisible to it and crash at runtime with "Call to invalid or unregistered
function" (first hit: 0x82E80DA8 during KernelState module launch).

XenonRecomp's corpus (xenon_recomp/work/recomp_output/) found these via its
gap-fill pass, so we mine it:

  missing = XR functions that are neither padding (.long 0x0 bodies only)
            nor present in ReXGlue's output (as a function OR an internal
            loc_ label inside a merged function)

Size = next XR function start - address. That is exact: XR emits padding runs
as their own stub "functions", so a real function's next neighbor starts where
its code (incl. alignment) ends.

Usage:
  gen_missing_functions.py --xr-dir .../recomp_output \
      --rx-dir .../civrev/generated/default --out functions_xr_gapfill.toml
"""
import argparse
import glob
import os
import re
import sys

FUNC_XR = re.compile(r'PPC_FUNC_IMPL\(__imp__sub_([0-9A-F]{8})\)\s*\{(.*?)\n\}', re.S)
FUNC_RX = re.compile(r'\{ 0x([0-9A-F]{8}), sub_[0-9A-F]{8} \}')
LABEL_RX = re.compile(r'loc_([0-9A-F]{8})')


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument('--xr-dir', required=True, help='XenonRecomp recomp_output dir')
    ap.add_argument('--rx-dir', required=True, help='ReXGlue generated/default dir')
    ap.add_argument('--out', required=True)
    args = ap.parse_args()

    xr_addrs = []
    padding = set()
    for fn in sorted(glob.glob(os.path.join(args.xr_dir, 'ppc_recomp.*.cpp'))):
        with open(fn) as f:
            txt = f.read()
        for m in FUNC_XR.finditer(txt):
            addr, body = m.group(1), m.group(2)
            xr_addrs.append(addr)
            ops = [l.strip() for l in body.splitlines() if l.strip().startswith('//')]
            if ops and all(o == '// .long 0x0' for o in ops):
                padding.add(addr)
    xr_addrs = sorted(set(xr_addrs))
    if not xr_addrs:
        print('no XR functions found — wrong --xr-dir?', file=sys.stderr)
        return 1

    rx_present = set()
    init_cpp = os.path.join(args.rx_dir, 'civrev_init.cpp')
    with open(init_cpp) as f:
        rx_present.update(FUNC_RX.findall(f.read()))
    for fn in glob.glob(os.path.join(args.rx_dir, 'civrev_recomp.*.cpp')):
        with open(fn) as f:
            rx_present.update(LABEL_RX.findall(f.read()))

    nxt = {a: xr_addrs[i + 1] for i, a in enumerate(xr_addrs[:-1])}
    missing = [a for a in xr_addrs
               if a not in padding and a not in rx_present and a in nxt]

    with open(args.out, 'w') as out:
        out.write(
            '# GENERATED by tools/gen_missing_functions.py — do not hand-edit.\n'
            '# Functions present in the XenonRecomp corpus but invisible to\n'
            "# ReXGlue's reachability analysis (data-referenced only: vtables,\n"
            '# function-pointer tables). Sizes are exact XR boundaries.\n'
            '[functions]\n')
        for a in missing:
            size = int(nxt[a], 16) - int(a, 16)
            out.write(f'0x{a} = {{ size = 0x{size:X} }}\n')
    print(f'{len(missing)} entries -> {args.out}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
